// ─────────────────────────────────────────────
//  SEED DATA — static fixtures for all collections
// ─────────────────────────────────────────────

const USERS = [
  // Admin
  {
    email: 'admin@dementiacare.in',
    password: 'Admin@1234',
    role: 'admin',
    firstName: 'Rajesh',
    lastName: 'Sharma',
    phone: '9876543210',
    department: 'Administration',
    location: 'Delhi',
    employeeId: 'EMP-001',
    bio: 'System administrator for DementiaCare AI platform.',
  },
  // Doctors
  {
    email: 'dr.arora@dementiacare.in',
    password: 'Doctor@1234',
    role: 'doctor',
    firstName: 'Priya',
    lastName: 'Arora',
    phone: '9812345678',
    department: 'Neurology',
    specialization: 'Behavioural Neurology & Dementia Care',
    licenseNo: 'MCI-NEU-2019-04521',
    hospital: 'AIIMS New Delhi',
    experience: '12 years',
    opdTiming: 'Mon-Fri 09:00-13:00',
    ward: 'Neuro OPD Block B',
    location: 'Delhi',
    employeeId: 'DOC-001',
  },
  {
    email: 'dr.menon@dementiacare.in',
    password: 'Doctor@1234',
    role: 'doctor',
    firstName: 'Suresh',
    lastName: 'Menon',
    phone: '9823456789',
    department: 'General Medicine',
    specialization: 'Geriatric Medicine',
    licenseNo: 'MCI-GEN-2015-08734',
    hospital: 'Fortis Healthcare Mumbai',
    experience: '18 years',
    opdTiming: 'Tue-Sat 10:00-14:00',
    ward: 'Geriatrics Ward 3',
    location: 'Mumbai',
    employeeId: 'DOC-002',
  },
  // Caregivers
  {
    email: 'caregiver.lakshmi@dementiacare.in',
    password: 'Care@1234',
    role: 'caregiver',
    firstName: 'Lakshmi',
    lastName: 'Nair',
    phone: '9845671234',
    department: 'Caregiving',
    location: 'Kochi',
    employeeId: 'CG-001',
  },
  {
    email: 'caregiver.anita@dementiacare.in',
    password: 'Care@1234',
    role: 'caregiver',
    firstName: 'Anita',
    lastName: 'Desai',
    phone: '9856782345',
    department: 'Caregiving',
    location: 'Pune',
    employeeId: 'CG-002',
  },
  {
    email: 'caregiver.ravi@dementiacare.in',
    password: 'Care@1234',
    role: 'caregiver',
    firstName: 'Ravi',
    lastName: 'Kumar',
    phone: '9867893456',
    department: 'Caregiving',
    location: 'Bangalore',
    employeeId: 'CG-003',
  },
  // Patients
  {
    email: 'patient.mohan@dementiacare.in',
    password: 'Patient@1234',
    role: 'patient',
    firstName: 'Mohan',
    lastName: 'Gupta',
    phone: '9901234567',
    location: 'Delhi',
  },
  {
    email: 'patient.savitri@dementiacare.in',
    password: 'Patient@1234',
    role: 'patient',
    firstName: 'Savitri',
    lastName: 'Iyer',
    phone: '9912345678',
    location: 'Chennai',
  },
  {
    email: 'patient.baldev@dementiacare.in',
    password: 'Patient@1234',
    role: 'patient',
    firstName: 'Baldev',
    lastName: 'Singh',
    phone: '9923456789',
    location: 'Amritsar',
  },
  {
    email: 'patient.kamala@dementiacare.in',
    password: 'Patient@1234',
    role: 'patient',
    firstName: 'Kamala',
    lastName: 'Rao',
    phone: '9934567890',
    location: 'Hyderabad',
  },
  {
    email: 'patient.ramesh@dementiacare.in',
    password: 'Patient@1234',
    role: 'patient',
    firstName: 'Ramesh',
    lastName: 'Joshi',
    phone: '9945678901',
    location: 'Jaipur',
  },
];

const PATIENT_PROFILES = [
  {
    firstName: 'Mohan', lastName: 'Gupta',
    phone: '9901234567', dateOfBirth: '1948-03-12',
    gender: 'Male', address: '14/2 Lajpat Nagar, New Delhi - 110024',
    bloodGroup: 'B+', age: '78', weight: '68 kg', height: '5\'7"',
    conditions: 'Alzheimer\'s Disease - Stage 3 (Moderate)',
    allergies: 'Penicillin, Sulfa drugs',
    currentMedications: 'Donepezil 10mg, Memantine 10mg',
    primaryDoctor: 'Dr. Priya Arora',
    lastVisit: '2026-06-10', nextAppointment: '2026-07-15',
    emergency: {
      contactName: 'Sunil Gupta', relationship: 'Son',
      contactPhone: '9811223344', contactEmail: 'sunil.gupta@gmail.com',
      altContactName: 'Meena Gupta', altRelationship: 'Daughter-in-law', altPhone: '9822334455',
    },
  },
  {
    firstName: 'Savitri', lastName: 'Iyer',
    phone: '9912345678', dateOfBirth: '1950-07-22',
    gender: 'Female', address: '7 Anna Nagar East, Chennai - 600102',
    bloodGroup: 'O+', age: '75', weight: '55 kg', height: '5\'2"',
    conditions: 'Vascular Dementia - Moderate Stage',
    allergies: 'Aspirin, Shellfish',
    currentMedications: 'Rivastigmine 6mg, Amlodipine 5mg',
    primaryDoctor: 'Dr. Priya Arora',
    lastVisit: '2026-06-05', nextAppointment: '2026-07-20',
    emergency: {
      contactName: 'Venkat Iyer', relationship: 'Son',
      contactPhone: '9833445566', contactEmail: 'venkat.iyer@gmail.com',
      altContactName: 'Padma Iyer', altRelationship: 'Daughter', altPhone: '9844556677',
    },
  },
  {
    firstName: 'Baldev', lastName: 'Singh',
    phone: '9923456789', dateOfBirth: '1945-11-05',
    gender: 'Male', address: '23 Golden Avenue, Amritsar - 143001',
    bloodGroup: 'A+', age: '80', weight: '72 kg', height: '5\'9"',
    conditions: 'Lewy Body Dementia - Early Moderate Stage',
    allergies: 'Latex, NSAIDs',
    currentMedications: 'Rivastigmine 4.5mg, Quetiapine 25mg',
    primaryDoctor: 'Dr. Suresh Menon',
    lastVisit: '2026-05-28', nextAppointment: '2026-07-08',
    emergency: {
      contactName: 'Harpreet Singh', relationship: 'Son',
      contactPhone: '9855667788', contactEmail: 'harpreet.singh@gmail.com',
      altContactName: 'Gurpreet Kaur', altRelationship: 'Daughter', altPhone: '9866778899',
    },
  },
  {
    firstName: 'Kamala', lastName: 'Rao',
    phone: '9934567890', dateOfBirth: '1952-04-18',
    gender: 'Female', address: '45 Banjara Hills, Hyderabad - 500034',
    bloodGroup: 'AB+', age: '74', weight: '58 kg', height: '5\'1"',
    conditions: 'Alzheimer\'s Disease - Stage 2 (Mild)',
    allergies: 'Codeine, Tree nuts',
    currentMedications: 'Donepezil 5mg, Vitamin D 1000IU',
    primaryDoctor: 'Dr. Suresh Menon',
    lastVisit: '2026-06-18', nextAppointment: '2026-07-25',
    emergency: {
      contactName: 'Kiran Rao', relationship: 'Son',
      contactPhone: '9877889900', contactEmail: 'kiran.rao@gmail.com',
      altContactName: 'Sudha Rao', altRelationship: 'Daughter', altPhone: '9888990011',
    },
  },
  {
    firstName: 'Ramesh', lastName: 'Joshi',
    phone: '9945678901', dateOfBirth: '1947-09-30',
    gender: 'Male', address: '8 Civil Lines, Jaipur - 302006',
    bloodGroup: 'O-', age: '78', weight: '65 kg', height: '5\'6"',
    conditions: 'Frontotemporal Dementia - Mild Stage',
    allergies: 'Erythromycin, Dairy',
    currentMedications: 'Sertraline 50mg, Memantine 5mg',
    primaryDoctor: 'Dr. Priya Arora',
    lastVisit: '2026-06-12', nextAppointment: '2026-07-18',
    emergency: {
      contactName: 'Deepak Joshi', relationship: 'Son',
      contactPhone: '9899001122', contactEmail: 'deepak.joshi@gmail.com',
      altContactName: 'Sunita Joshi', altRelationship: 'Daughter-in-law', altPhone: '9900112233',
    },
  },
];

const MEDICINES = [
  {
    name: 'Aricept', generic: 'Donepezil HCl', category: 'Anti-Dementia',
    schedule: 'Schedule H', dosage: '10mg once daily at bedtime',
    indication: 'Moderate-to-severe Alzheimer\'s Disease',
    licensed: true, form: 'Oral Tablet',
    monitor: 'Bradycardia, GI upset, sleep disturbances',
  },
  {
    name: 'Ebixa', generic: 'Memantine HCl', category: 'Anti-Dementia',
    schedule: 'Schedule H', dosage: '10mg twice daily',
    indication: 'Moderate-to-severe Alzheimer\'s and Vascular Dementia',
    licensed: true, form: 'Oral Tablet',
    monitor: 'Dizziness, headache, confusion, constipation',
  },
  {
    name: 'Exelon', generic: 'Rivastigmine', category: 'Anti-Dementia',
    schedule: 'Schedule H', dosage: '6mg twice daily with meals',
    indication: 'Lewy Body Dementia and Alzheimer\'s Disease',
    licensed: true, form: 'Oral Capsule',
    monitor: 'Nausea, vomiting, weight loss, dizziness',
  },
  {
    name: 'Seroquel', generic: 'Quetiapine fumarate', category: 'Antipsychotic',
    schedule: 'Schedule H1', dosage: '25mg at bedtime',
    indication: 'Psychosis and agitation in Lewy Body Dementia',
    licensed: true, form: 'Oral Tablet',
    monitor: 'Sedation, orthostatic hypotension, metabolic changes',
  },
  {
    name: 'Zoloft', generic: 'Sertraline HCl', category: 'Antidepressant',
    schedule: 'Schedule H', dosage: '50mg once daily with breakfast',
    indication: 'Depression and anxiety in Frontotemporal Dementia',
    licensed: false, form: 'Oral Tablet',
    monitor: 'GI disturbances, insomnia, serotonin syndrome risk',
  },
  {
    name: 'Norvasc', generic: 'Amlodipine besylate', category: 'Anti-Dementia',
    schedule: 'Schedule H', dosage: '5mg once daily',
    indication: 'Hypertension management in Vascular Dementia',
    licensed: false, form: 'Oral Tablet',
    monitor: 'Peripheral oedema, flushing, hypotension',
  },
  {
    name: 'Rivotril', generic: 'Clonazepam', category: 'Benzodiazepine',
    schedule: 'Schedule X', dosage: '0.5mg at bedtime as needed',
    indication: 'Seizure prophylaxis and severe agitation',
    licensed: true, form: 'Oral Tablet',
    monitor: 'Excessive sedation, fall risk, dependence potential',
  },
  {
    name: 'Stilnox', generic: 'Zolpidem tartrate', category: 'Hypnotic',
    schedule: 'Schedule X', dosage: '5mg at bedtime',
    indication: 'Short-term management of insomnia in dementia patients',
    licensed: true, form: 'Oral Tablet',
    monitor: 'Complex sleep behaviours, next-day drowsiness, fall risk',
  },
];

const STAFF_DATA = [
  {
    name: 'Dr. Priya Arora', role: 'Doctor',
    designation: 'Senior Consultant Neurologist',
    department: 'Neurology',
    license: 'MCI-NEU-2019-04521',
    phone: '9812345678',
    email: 'priya.arora.staff@dementiacare.in',
    experience: '12 years', status: 'Active', avatar: '👩‍⚕️',
  },
  {
    name: 'Dr. Suresh Menon', role: 'Doctor',
    designation: 'Senior Consultant – Geriatric Medicine',
    department: 'General Medicine',
    license: 'MCI-GEN-2015-08734',
    phone: '9823456789',
    email: 'suresh.menon.staff@dementiacare.in',
    experience: '18 years', status: 'Active', avatar: '👨‍⚕️',
  },
  {
    name: 'Meenakshi Pillai', role: 'Nurse',
    designation: 'Head Nurse – Neurology Ward',
    department: 'Neurology',
    license: 'NCI-2018-07231',
    phone: '9834561234',
    email: 'meenakshi.pillai@dementiacare.in',
    experience: '9 years', status: 'Active', avatar: '👩‍⚕️',
  },
  {
    name: 'Arvind Tiwari', role: 'Nurse',
    designation: 'Staff Nurse – Geriatrics',
    department: 'General Medicine',
    license: 'NCI-2020-09512',
    phone: '9845672345',
    email: 'arvind.tiwari@dementiacare.in',
    experience: '6 years', status: 'Active', avatar: '👨‍⚕️',
  },
  {
    name: 'Dr. Sunanda Krishnan', role: 'Psychologist',
    designation: 'Clinical Psychologist',
    department: 'Psychiatry & Cognitive Health',
    license: 'RCI-2016-11423',
    phone: '9856783456',
    email: 'sunanda.krishnan@dementiacare.in',
    experience: '10 years', status: 'Active', avatar: '👩‍⚕️',
  },
  {
    name: 'Farhan Qureshi', role: 'Psychiatric Social Worker',
    designation: 'Senior Psychiatric Social Worker',
    department: 'Social & Community Care',
    license: 'RCI-SW-2017-05634',
    phone: '9867894567',
    email: 'farhan.qureshi@dementiacare.in',
    experience: '8 years', status: 'On Leave', avatar: '👨‍💼',
  },
];

module.exports = { USERS, PATIENT_PROFILES, MEDICINES, STAFF_DATA };
